name: Chairs
version: 1.5b
description: Let players sit on stairs and slabs.
authors: spoothie, cnaude
main: net.spoothie.chairs.Chairs
commands:
    chairs:
        description: Reloads the Chairs configuration file.
        usage: /chairs reload